forci_remember_me_token_list:
    path:      /list
    defaults: { _controller: ForciRememberMeBundle:RememberMeToken:list }

forci_remember_me_token_view:
    path:      /{id}/view
    defaults: { _controller: ForciRememberMeBundle:RememberMeToken:view }

forci_remember_me_token_delete:
    path:      /{id}/delete
    defaults:  { _controller: ForciRememberMeBundle:RememberMeToken:delete }

forci_remember_me_token_refresh:
    path:      /{id}/refresh
    defaults:  { _controller: ForciRememberMeBundle:RememberMeToken:refresh }